import Header from '@/components/Header'
import '../styles/globals.css'

export const metadata = {
  title: 'ImageGPT | Generate Images',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}</body>
    </html>
  )
}
